### ISSUE TITLE
Firewall and System Apps

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#14]
We left out system apps because they end up causing more confusion (there are too many and some even critical), but that has meant leaving out other pre-installed apps too.

Users want to firewall those pre-installed _System Apps_ predominantly because they can't be uninstalled (in some cases, can't even be disabled). Probably show as a separate category? Or, show only when a specific UI is toggled to view _System Apps_ (like in NetGuard)?

**Comment by hussainmohd-a** [comment]
Included System apps in firewall screen.
