### ISSUE TITLE
Network Monitor

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#16]
Like the DNS log screen, there needs to be an indicator of how many apps are blocked, connections blocked, and so on in the main configure firewall screen. Also, may be, arrange the list to keep blocked apps at the top, and the rest at the bottom (See: Glasswire)?

#42

**Comment by ignoramous** [comment]
For a list of UIDs that may make requests but not have a package name, see: [android_filesystem_config.h](https://cs.android.com/android/platform/superproject/+/master:system/core/libcutils/include/private/android_filesystem_config.h).

[`android.uid.system`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/AndroidManifest.xml;l=21) does have a package-name, though, which is `android`.

**Comment by hussainmohd-a** [comment]
Introduced network monitor screen which will provide the details on the app, timestamp, IP, port, type of connection, and flag. Blocked connections are highlighted with an indicator. 

Need to introduce some stats like per app connections blocked, filtering based on IP.

**Comment by ignoramous** [comment]
> Need to introduce some stats like per app connections blocked, filtering based on IP.

#42
