### ISSUE TITLE
Firewall and Shared UIDs

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#30]
[BraveVPNService#isUidBlocked](https://github.com/celzero/brave-android-app/blob/master/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L143) needs to account for the fact that there can be [multiple packages (apps) with the same uid](https://stackoverflow.com/questions/9783765/what-is-shareduserid-in-android-and-how-is-it-used). See: [PackageManager#getPackagesForUid](https://developer.android.com/reference/android/content/pm/PackageManager?hl=en#getPackagesForUid(int)).

A consistent behaviour would be:
1. Show all apps with shared-uid together on the firewall screen. If they are across different categories then show the group once each across those categories.
2. When blocking any one app with shared-uid, block all, and make that much clear to the user.
3. In ConnTrack #3 make sure to bunch these apps together in the report.

**Comment by hussainmohd-a** [comment]
UID check is made against the blocked list and return boolean value whether to block/allow.
