### ISSUE TITLE
Firewall implementation missing for Android 8+

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#31]
[BraveVPNService#block](https://github.com/celzero/brave-android-app/blob/master/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L122-L124) will not block any app on Android versions below 10.

This needs to be fixed: On Android versions below 10 `uid` is retrieved from `proc/net/[tcp|udp]` to find owner of any given connection See: #1

**Comment by hussainmohd-a** [comment]
Firewall Implementation for 8+ - UID check is made against the blocked list and return boolean value whether to block/allow.
