### ISSUE TITLE
Refactor the Firewall Screen

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#4]
Refactor the current Firewall screen to rid of two different app lists and possibly merge them into one single list. This has been a source of lot of pain in terms of handling Category-wise allow/disallow. Merging the lists would simplify the confusing UI and as a bonus simplify the existing business logic.

**Comment by hussainmohd-a** [comment]
Firewall Screen:
* Removed the category and app list from firewall screen
* Introduced expandable list view which will show the app category and list of apps in the category.
* Livedata mapping with the database. (AppInfoDAO and CategoryInfoDAO).
* Prompt dialog box when an app with same UID is blocked/unblocked. Dialog box will contain list of apps blocked/unblocked along with the selected app.
* Included System apps also in firewall screen
