### ISSUE TITLE
Firewall apps not-in-use behaviour is too crude

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#65]
Today, BraveDNS blocks every request other than requests made by the UID of any app currently in the foreground.

This is crude since system service can never be in the foreground and would mercilessly get blocked. Ref the ranges here: [system/core/private/android_filesystem_config.h](http://androidxref.com/9.0.0_r3/xref/system/core/include/private/android_filesystem_config.h).

Only block the UIDs in the app ranges when this feature is enabled. Probably ask the user if they want to block all system apps not in the foreground too.

**Comment by hussainmohd-a** [comment]
Universal firewall for "allow apps on background" logic is modified. Now the uid's which are in range from APP_START to APP_END is included. Now it works as originally intended.
