### ISSUE TITLE
Name is confusing

### ISSUE THREAD

**Issue by lionirdeadman** [celzero/brave-android-app#69]
When I first heard of this app, My mind immediately went to Brave, the browser. This is unfortunate because it is a good name otherwise.

What to do?

**Comment by ignoramous** [comment]
It is unfortunate, though I see why any one would think that. We are sticking with the name because we like it, unless of course, until we can't.

There's an about page in the app that should alleviate any misattribution. We also mention "Not affiliated with Brave.com in any way or form" on our website footer...

What else should we do, do you think?

**Comment by lionirdeadman** [comment]
Adding a "By X" at the end at least on the play store would resolve this, I think?

**Comment by ignoramous** [comment]
Great idea.

PlayStore already shows the developers are "celzero" ... right below the title though. I guess that doesn't help much?

**Comment by lionirdeadman** [comment]
Hm, right, they do but it's not really prominent?

**Comment by ignoramous** [comment]
I think we might just as well change our name given all the confusion.

Do you have any good ones? (I prefer if there's a .com domain available for the name).

**Comment by lionirdeadman** [comment]
Names are not my strong point but why not just Celzero DNS? It could then be shown on the celzero.com which you already own, right?

**Comment by ignoramous** [comment]
zerodns?

**Comment by lionirdeadman** [comment]
Here's some thoughts about some of those choices

> MazeDNS

I'm not sure what is implied here.
> NotJustAnotherVPN

Calling it a VPN in any shape would be misleading.
> DIE: Dns prIvacy sEcurity
> SPAY: dnS PrivAcY
> NASTY: dNs privAcy SecuriTY

I would avoid these since they're not keywords that we'd want associated, I think and the acronyms make little sense.
> BraveWall

This has the same issue as BraveDNS
> Zero.Zero.Zero.Zero / 0.0.0.0

This seems to imply it's only a DNS and competitor to Cloudflare which is not the case at all.
> DareDNS

I like this name but it could be a bit weird because of D.A.R.E.

> ACS tools (anti-censorship / anti-surveillance tool)

I kinda like the idea of calling it tools rather than DNS since it offers more than a DNS but I don't think we circumvent censorship in any way.

The other suggestions I have no feelings for or against.

**Comment by ignoramous** [comment]
We've begun the rename. Redirecting the DNS traffic to the new domain is going to take a long while... Dread it. Hate it. Sigh.

Ref: https://twitter.com/bravedns
