### ISSUE TITLE
Fail-over DNS-over-HTTPs

### ISSUE THREAD

**Issue by smartyn13r** [celzero/brave-android-app#73]
User should be able to choose a list of DNS-over-HTTPs servers and app should connect to one of them depending on failures route traffic to others

**Comment by ignoramous** [comment]
Just to be clear, you mean to say the app should round-robin between multiple DNS servers and always choose depending on lowest latency and error rates?

**Comment by smartyn13r** [comment]
Yes

**Comment by ignoramous** [comment]
Gotcha, see: #40 

Closing this as a duplicate.
