### ISSUE TITLE
AccessibilityService#onInterrupt Crash

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#75]
Handle `AccessibilityService#onInterrupt` as its required by Android.

[These interrupts can be ignored](https://developer.android.com/guide/topics/ui/accessibility/service) since we do not really use it for _accessibility_ but to enforce firewall rules (on apps in the background).

**Comment by Ch4t4r** [comment]
Just a heads-up. No idea how relevant it is still, though.

https://www.androidcentral.com/apps-using-accessibility-services-could-be-removed-play-store

**Comment by hussainmohd-a** [comment]
Accessibility services requires implementation of onInterrupt() method. Included callback for interrupting the accessibility feedback.
