### ISSUE TITLE
Use LiveData to track live counters

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#8]
May be [LiveData](https://developer.android.com/topic/libraries/architecture/livedata) make our lives easier?

The live counters appears on the homescreen and show total dns queries, percentage queries blocked, number of apps blocked and so on... May be there's a use for `LiveData` elsewhere too, like in the Firewall screen with [ConnTrack](https://github.com/celzero/brave-android-app/issues/3)?

**Comment by hussainmohd-a** [comment]
Handlers are removed from the Homescreen and Firewall screen. Introduced live data to update the value.
